name: commandline_splitter
description: Splits command line string into a list of individual parts suitable for using with Process.start or Process.run.
version: 1.5.2
homepage: https://github.com/desktop-dart/commandline_splitter
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
